export interface UserType{
    address:{
        street:string
        number:number
        city:string
        geolocation:{
            lat:string
            long:string
        }
    }
    id:number
    name:{
        firstname:string
        lastname:string
    },
    email:string
    password:string
    phone:string
    username:string
}